### ISSUE TITLE
CI: Some unit tests fail due to timing issues

### ISSUE THREAD

**Issue by brannon** [cloudfoundry/IronFrame#4]
I have had a hard time reproducing these failures locally, but on our internal TeamCity CI server, these tests fail occasionally.  We should try to fix these.

See below for TeamCity build logs:

```
[IronFrame.Utilities.JobObjectLimitsTests+Notifications.FiresSecondNotificationWhenLimitIncreases] System.TimeoutException : The task did not complete within the timeout period of 1000ms
   at AssertHelper.<CompletesWithinTimeoutAsync>d__0.MoveNext() in d:\BuildAgent\work\d6bfc8c44d3dfaed\if_warden\IronFrame\IronFrame.Test\TestSupport\AssertHelper.cs:line 12
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IronFrame.Utilities.JobObjectLimitsTests.Notifications.<FiresSecondNotificationWhenLimitIncreases>d__8.MoveNext() in d:\BuildAgent\work\d6bfc8c44d3dfaed\if_warden\IronFrame\IronFrame.Test\Utilities\JobObjectLimitsTests.cs:line 81
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__0(Object state)
```

```
MessageTransportTest.ReceivedErrorResponseInvokesResponseCallback	
 
System.TimeoutException : The task did not complete within the timeout period of 1000ms
   at AssertHelper.<CompletesWithinTimeoutAsync>d__0.MoveNext() in d:\BuildAgent\work\d6bfc8c44d3dfaed\if_warden\IronFrame\IronFrame.Test\TestSupport\AssertHelper.cs:line 12
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IronFrame.Messaging.MessageTransportTest.<ReceivedErrorResponseInvokesResponseCallback>d__3f.MoveNext() in d:\BuildAgent\work\d6bfc8c44d3dfaed\if_warden\IronFrame\IronFrame.Test\Messaging\MessageTransportTest.cs:line 135
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__0(Object state)
```

**Comment by aminjam** [comment]
Closing this issue due to inactivity. Please let us know if you are still experiencing this issue.
